-- Transactional outbox for settlement domain events (settlement.completed).
-- Mirror of transaction-mgmt V002 — H2 (MODE=PostgreSQL) and PostgreSQL portable; payload is TEXT
-- (canonical event JSON). Rows are written in the same txn as the batch and drained by OutboxPublisher.
CREATE TABLE outbox (
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    aggregate_id  VARCHAR(64)  NOT NULL,
    event_type    VARCHAR(64)  NOT NULL,
    payload       TEXT         NOT NULL,
    created_at    TIMESTAMP    NOT NULL,
    published_at  TIMESTAMP    NULL
);

-- Drain reads unpublished rows oldest-first; this index keeps that scan cheap.
CREATE INDEX idx_outbox_unpublished ON outbox (published_at);
