package com.gme.pay.scheme.zeropay.batch;

import com.gme.pay.scheme.zeropay.adapter.ZeroPayAdapterProperties;
import com.gme.pay.scheme.zeropay.adapter.ZeroPaySchemeAdapter;
import com.gme.pay.scheme.zeropay.adapter.model.BatchFile;
import com.gme.pay.scheme.zeropay.adapter.model.BatchType;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;
import org.springframework.boot.autoconfigure.condition.ConditionalOnBean;
import org.springframework.scheduling.annotation.EnableScheduling;
import org.springframework.scheduling.annotation.Scheduled;
import org.springframework.stereotype.Component;

import java.time.LocalDate;
import java.time.ZoneId;

/**
 * KST batch-window scheduler for ZeroPay ZP00xx files.
 *
 * <p>Windows (all times Asia/Seoul, KST = UTC+9):
 * <pre>
 *  ~02:00  ZP0011 payment result   + ZP0021 refund result   → outbound
 *  ~05:00  ZP0061 settlement request (morning)              → outbound
 *  ~14:00  ZP0063 settlement request (afternoon)            → outbound
 *  ~22:00  ZP0065 payment detail   + ZP0066 refund detail   → outbound
 * </pre>
 * </p>
 *
 * <p>Inbound files (ZP0012, ZP0022, ZP0062, ZP0064) are polled by separate fetch jobs
 * or can be triggered manually — they are not generated by the scheduler.</p>
 *
 * <p>The scheduler fires only when
 * {@code gmepay.scheme.zeropay.batch.enabled=true} (default {@code false}).
 * This gate is checked at runtime so no restart is required to re-enable.</p>
 *
 * <p>Requires {@link ZeroPaySchemeAdapter} to be in the Spring context
 * (i.e. {@code adapter.zeropay.enabled=true}).</p>
 */
@Component
@EnableScheduling
@ConditionalOnBean(ZeroPaySchemeAdapter.class)
public class ZeroPayBatchScheduler {

    private static final Logger log = LoggerFactory.getLogger(ZeroPayBatchScheduler.class);
    private static final ZoneId KST = ZoneId.of("Asia/Seoul");

    private final ZeroPaySchemeAdapter adapter;
    private final ZeroPayAdapterProperties properties;

    public ZeroPayBatchScheduler(ZeroPaySchemeAdapter adapter,
                                 ZeroPayAdapterProperties properties) {
        this.adapter    = adapter;
        this.properties = properties;
    }

    // -----------------------------------------------------------------------
    // ~02:00 KST — ZP0011 + ZP0021 (payment/refund result registration)
    // -----------------------------------------------------------------------

    /**
     * Generates and transfers ZP0011 (payment result) at ~02:00 KST.
     *
     * <p>Cron: {@code 0 0 2 * * *} in zone {@code Asia/Seoul}.</p>
     */
    @Scheduled(cron = "0 0 2 * * *", zone = "Asia/Seoul")
    public void generatePaymentResult() {
        if (!properties.isBatchEnabled()) {
            log.debug("ZeroPay batch disabled — skipping ZP0011");
            return;
        }
        LocalDate businessDate = LocalDate.now(KST);
        log.info("[Scheduler] ZP0011 start for {}", businessDate);
        try {
            BatchFile file = adapter.generatePaymentResultFile(BatchType.ZP0011, businessDate);
            adapter.transferOutbound(file, null);
            log.info("[Scheduler] ZP0011 complete: {} records", file.recordCount());
        } catch (Exception e) {
            log.error("[Scheduler] ZP0011 failed for {}: {}", businessDate, e.getMessage(), e);
        }
    }

    /**
     * Generates and transfers ZP0021 (refund result) at ~02:00 KST.
     *
     * <p>Cron: {@code 0 2 2 * * *} in zone {@code Asia/Seoul} (2 minutes after ZP0011).</p>
     */
    @Scheduled(cron = "0 2 2 * * *", zone = "Asia/Seoul")
    public void generateRefundResult() {
        if (!properties.isBatchEnabled()) {
            log.debug("ZeroPay batch disabled — skipping ZP0021");
            return;
        }
        LocalDate businessDate = LocalDate.now(KST);
        log.info("[Scheduler] ZP0021 start for {}", businessDate);
        try {
            BatchFile file = adapter.generateRefundResultFile(BatchType.ZP0021, businessDate);
            adapter.transferOutbound(file, null);
            log.info("[Scheduler] ZP0021 complete: {} records", file.recordCount());
        } catch (Exception e) {
            log.error("[Scheduler] ZP0021 failed for {}: {}", businessDate, e.getMessage(), e);
        }
    }

    // -----------------------------------------------------------------------
    // ~05:00 KST — ZP0061 (morning settlement request)
    // -----------------------------------------------------------------------

    /**
     * Generates and transfers ZP0061 (morning settlement request) at ~05:00 KST.
     *
     * <p>Cron: {@code 0 0 5 * * *} in zone {@code Asia/Seoul}.</p>
     */
    @Scheduled(cron = "0 0 5 * * *", zone = "Asia/Seoul")
    public void generateMorningSettlementRequest() {
        if (!properties.isBatchEnabled()) {
            log.debug("ZeroPay batch disabled — skipping ZP0061");
            return;
        }
        LocalDate businessDate = LocalDate.now(KST);
        log.info("[Scheduler] ZP0061 start for {}", businessDate);
        try {
            BatchFile file = adapter.generateSettlementRequestFile(BatchType.ZP0061, businessDate);
            adapter.transferOutbound(file, null);
            log.info("[Scheduler] ZP0061 complete: {} merchant records", file.recordCount());
        } catch (Exception e) {
            log.error("[Scheduler] ZP0061 failed for {}: {}", businessDate, e.getMessage(), e);
        }
    }

    // -----------------------------------------------------------------------
    // ~14:00 KST — ZP0063 (afternoon settlement request)
    // -----------------------------------------------------------------------

    /**
     * Generates and transfers ZP0063 (afternoon settlement request) at ~14:00 KST.
     *
     * <p>Cron: {@code 0 0 14 * * *} in zone {@code Asia/Seoul}.</p>
     */
    @Scheduled(cron = "0 0 14 * * *", zone = "Asia/Seoul")
    public void generateAfternoonSettlementRequest() {
        if (!properties.isBatchEnabled()) {
            log.debug("ZeroPay batch disabled — skipping ZP0063");
            return;
        }
        LocalDate businessDate = LocalDate.now(KST);
        log.info("[Scheduler] ZP0063 start for {}", businessDate);
        try {
            BatchFile file = adapter.generateSettlementRequestFile(BatchType.ZP0063, businessDate);
            adapter.transferOutbound(file, null);
            log.info("[Scheduler] ZP0063 complete: {} merchant records", file.recordCount());
        } catch (Exception e) {
            log.error("[Scheduler] ZP0063 failed for {}: {}", businessDate, e.getMessage(), e);
        }
    }

    // -----------------------------------------------------------------------
    // ~22:00 KST — ZP0065 + ZP0066 (payment/refund detail)
    // -----------------------------------------------------------------------

    /**
     * Generates and transfers ZP0065 (payment detail) at ~22:00 KST.
     *
     * <p>Cron: {@code 0 0 22 * * *} in zone {@code Asia/Seoul}.</p>
     */
    @Scheduled(cron = "0 0 22 * * *", zone = "Asia/Seoul")
    public void generatePaymentDetailFile() {
        if (!properties.isBatchEnabled()) {
            log.debug("ZeroPay batch disabled — skipping ZP0065");
            return;
        }
        LocalDate businessDate = LocalDate.now(KST);
        log.info("[Scheduler] ZP0065 start for {}", businessDate);
        try {
            BatchFile file = adapter.generatePaymentResultFile(BatchType.ZP0065, businessDate);
            adapter.transferOutbound(file, null);
            log.info("[Scheduler] ZP0065 complete: {} records", file.recordCount());
        } catch (Exception e) {
            log.error("[Scheduler] ZP0065 failed for {}: {}", businessDate, e.getMessage(), e);
        }
    }

    /**
     * Generates and transfers ZP0066 (refund detail) at ~22:02 KST (2 minutes after ZP0065).
     *
     * <p>Cron: {@code 0 2 22 * * *} in zone {@code Asia/Seoul}.</p>
     */
    @Scheduled(cron = "0 2 22 * * *", zone = "Asia/Seoul")
    public void generateRefundDetailFile() {
        if (!properties.isBatchEnabled()) {
            log.debug("ZeroPay batch disabled — skipping ZP0066");
            return;
        }
        LocalDate businessDate = LocalDate.now(KST);
        log.info("[Scheduler] ZP0066 start for {}", businessDate);
        try {
            BatchFile file = adapter.generateRefundResultFile(BatchType.ZP0066, businessDate);
            adapter.transferOutbound(file, null);
            log.info("[Scheduler] ZP0066 complete: {} records", file.recordCount());
        } catch (Exception e) {
            log.error("[Scheduler] ZP0066 failed for {}: {}", businessDate, e.getMessage(), e);
        }
    }
}
