package com.gme.pay.scheme.zeropay.batch;

import com.gme.pay.scheme.zeropay.adapter.ZeroPayAdapterProperties;
import com.gme.pay.scheme.zeropay.adapter.ZeroPaySchemeAdapter;
import com.gme.pay.scheme.zeropay.adapter.model.BatchFile;
import com.gme.pay.scheme.zeropay.adapter.model.BatchType;
import com.gme.pay.scheme.zeropay.adapter.model.TransferResult;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;
import org.springframework.boot.autoconfigure.condition.ConditionalOnBean;
import org.springframework.scheduling.annotation.EnableScheduling;
import org.springframework.scheduling.annotation.Scheduled;
import org.springframework.stereotype.Component;

import java.time.Instant;
import java.time.LocalDate;
import java.time.ZoneId;
import java.util.List;

/**
 * KST batch-window scheduler for ZeroPay ZP00xx files.
 *
 * <p>Windows (all times Asia/Seoul, KST = UTC+9):
 * <pre>
 *  ~02:00  ZP0011 payment result   + ZP0021 refund result   → outbound
 *  ~05:00  ZP0061 settlement request (morning)              → outbound
 *  ~14:00  ZP0063 settlement request (afternoon)            → outbound
 *  ~22:00  ZP0065 payment detail   + ZP0066 refund detail   → outbound
 * </pre>
 * </p>
 *
 * <p>Inbound files (ZP0012, ZP0022, ZP0062, ZP0064) are polled by separate fetch jobs
 * or can be triggered manually — they are not generated by the scheduler.</p>
 *
 * <p>The scheduler fires only when
 * {@code gmepay.scheme.zeropay.batch.enabled=true} (default {@code false}).
 * This gate is checked at runtime so no restart is required to re-enable.</p>
 *
 * <p>Requires {@link ZeroPaySchemeAdapter} to be in the Spring context
 * (i.e. {@code adapter.zeropay.enabled=true}).</p>
 */
@Component
@EnableScheduling
@ConditionalOnBean(ZeroPaySchemeAdapter.class)
public class ZeroPayBatchScheduler {

    private static final Logger log = LoggerFactory.getLogger(ZeroPayBatchScheduler.class);
    private static final ZoneId KST = ZoneId.of("Asia/Seoul");

    private final ZeroPaySchemeAdapter adapter;
    private final ZeroPayAdapterProperties properties;
    /** Persists the batch-file registry around generate/transfer; null in unit slices. */
    private final ZpBatchRegistrar registrar;
    /** Source of the day's records, used to stage ZP0011 detail lines; null in unit slices. */
    private final ZpBatchDataPort batchDataPort;

    /** Production constructor (Spring picks this — annotated per the two-ctor convention). */
    @org.springframework.beans.factory.annotation.Autowired
    public ZeroPayBatchScheduler(ZeroPaySchemeAdapter adapter,
                                 ZeroPayAdapterProperties properties,
                                 ZpBatchRegistrar registrar,
                                 ZpBatchDataPort batchDataPort) {
        this.adapter    = adapter;
        this.properties = properties;
        this.registrar  = registrar;
        this.batchDataPort = batchDataPort;
    }

    /** Test/legacy constructor without registry wiring. */
    public ZeroPayBatchScheduler(ZeroPaySchemeAdapter adapter,
                                 ZeroPayAdapterProperties properties) {
        this(adapter, properties, null, null);
    }

    /**
     * Registers the generated file (GENERATED), transfers it, then marks it TRANSMITTED.
     * Registry writes are best-effort — a registry failure never blocks the transfer.
     *
     * @param file          the generated batch file
     * @param zp0011Records ZP0011 detail records to stage, or null for non-ZP0011 types
     */
    private void registerTransferAndMark(BatchFile file, List<Zp0011Record> zp0011Records) {
        Long registryId = null;
        if (registrar != null) {
            String fileName = file.fileType().name()
                    + "_" + file.businessDate().toString().replace("-", "")
                    + "_" + String.format("%03d", file.sequenceNo()) + ".dat";
            registryId = registrar.registerGenerated(
                    file, fileName, Instant.now(), Instant.now().plusSeconds(3600), zp0011Records);
        }
        TransferResult result = adapter.transferOutbound(file, null);
        if (registrar != null && result != null && result.success()) {
            registrar.markTransmitted(registryId, Instant.now());
        }
    }

    // -----------------------------------------------------------------------
    // ~02:00 KST — ZP0011 + ZP0021 (payment/refund result registration)
    // -----------------------------------------------------------------------

    /**
     * Generates and transfers ZP0011 (payment result) at ~02:00 KST.
     *
     * <p>Cron: {@code 0 0 2 * * *} in zone {@code Asia/Seoul}.</p>
     */
    @Scheduled(cron = "0 0 2 * * *", zone = "Asia/Seoul")
    public void generatePaymentResult() {
        if (!properties.isBatchEnabled()) {
            log.debug("ZeroPay batch disabled — skipping ZP0011");
            return;
        }
        LocalDate businessDate = LocalDate.now(KST);
        log.info("[Scheduler] ZP0011 start for {}", businessDate);
        try {
            BatchFile file = adapter.generatePaymentResultFile(BatchType.ZP0011, businessDate);
            List<Zp0011Record> staged = batchDataPort != null
                    ? batchDataPort.fetchPaymentRecords(businessDate) : null;
            registerTransferAndMark(file, staged);
            log.info("[Scheduler] ZP0011 complete: {} records", file.recordCount());
        } catch (Exception e) {
            log.error("[Scheduler] ZP0011 failed for {}: {}", businessDate, e.getMessage(), e);
        }
    }

    /**
     * Generates and transfers ZP0021 (refund result) at ~02:00 KST.
     *
     * <p>Cron: {@code 0 2 2 * * *} in zone {@code Asia/Seoul} (2 minutes after ZP0011).</p>
     */
    @Scheduled(cron = "0 2 2 * * *", zone = "Asia/Seoul")
    public void generateRefundResult() {
        if (!properties.isBatchEnabled()) {
            log.debug("ZeroPay batch disabled — skipping ZP0021");
            return;
        }
        LocalDate businessDate = LocalDate.now(KST);
        log.info("[Scheduler] ZP0021 start for {}", businessDate);
        try {
            BatchFile file = adapter.generateRefundResultFile(BatchType.ZP0021, businessDate);
            registerTransferAndMark(file, null);
            log.info("[Scheduler] ZP0021 complete: {} records", file.recordCount());
        } catch (Exception e) {
            log.error("[Scheduler] ZP0021 failed for {}: {}", businessDate, e.getMessage(), e);
        }
    }

    // -----------------------------------------------------------------------
    // ~05:00 KST — ZP0061 (morning settlement request)
    // -----------------------------------------------------------------------

    /**
     * Generates and transfers ZP0061 (morning settlement request) at ~05:00 KST.
     *
     * <p>Cron: {@code 0 0 5 * * *} in zone {@code Asia/Seoul}.</p>
     */
    @Scheduled(cron = "0 0 5 * * *", zone = "Asia/Seoul")
    public void generateMorningSettlementRequest() {
        if (!properties.isBatchEnabled()) {
            log.debug("ZeroPay batch disabled — skipping ZP0061");
            return;
        }
        LocalDate businessDate = LocalDate.now(KST);
        log.info("[Scheduler] ZP0061 start for {}", businessDate);
        try {
            BatchFile file = adapter.generateSettlementRequestFile(BatchType.ZP0061, businessDate);
            registerTransferAndMark(file, null);
            log.info("[Scheduler] ZP0061 complete: {} merchant records", file.recordCount());
        } catch (Exception e) {
            log.error("[Scheduler] ZP0061 failed for {}: {}", businessDate, e.getMessage(), e);
        }
    }

    // -----------------------------------------------------------------------
    // ~14:00 KST — ZP0063 (afternoon settlement request)
    // -----------------------------------------------------------------------

    /**
     * Generates and transfers ZP0063 (afternoon settlement request) at ~14:00 KST.
     *
     * <p>Cron: {@code 0 0 14 * * *} in zone {@code Asia/Seoul}.</p>
     */
    @Scheduled(cron = "0 0 14 * * *", zone = "Asia/Seoul")
    public void generateAfternoonSettlementRequest() {
        if (!properties.isBatchEnabled()) {
            log.debug("ZeroPay batch disabled — skipping ZP0063");
            return;
        }
        LocalDate businessDate = LocalDate.now(KST);
        log.info("[Scheduler] ZP0063 start for {}", businessDate);
        try {
            BatchFile file = adapter.generateSettlementRequestFile(BatchType.ZP0063, businessDate);
            registerTransferAndMark(file, null);
            log.info("[Scheduler] ZP0063 complete: {} merchant records", file.recordCount());
        } catch (Exception e) {
            log.error("[Scheduler] ZP0063 failed for {}: {}", businessDate, e.getMessage(), e);
        }
    }

    // -----------------------------------------------------------------------
    // ~22:00 KST — ZP0065 + ZP0066 (payment/refund detail)
    // -----------------------------------------------------------------------

    /**
     * Generates and transfers ZP0065 (payment detail) at ~22:00 KST.
     *
     * <p>Cron: {@code 0 0 22 * * *} in zone {@code Asia/Seoul}.</p>
     */
    @Scheduled(cron = "0 0 22 * * *", zone = "Asia/Seoul")
    public void generatePaymentDetailFile() {
        if (!properties.isBatchEnabled()) {
            log.debug("ZeroPay batch disabled — skipping ZP0065");
            return;
        }
        LocalDate businessDate = LocalDate.now(KST);
        log.info("[Scheduler] ZP0065 start for {}", businessDate);
        try {
            BatchFile file = adapter.generatePaymentResultFile(BatchType.ZP0065, businessDate);
            registerTransferAndMark(file, null);
            log.info("[Scheduler] ZP0065 complete: {} records", file.recordCount());
        } catch (Exception e) {
            log.error("[Scheduler] ZP0065 failed for {}: {}", businessDate, e.getMessage(), e);
        }
    }

    /**
     * Generates and transfers ZP0066 (refund detail) at ~22:02 KST (2 minutes after ZP0065).
     *
     * <p>Cron: {@code 0 2 22 * * *} in zone {@code Asia/Seoul}.</p>
     */
    @Scheduled(cron = "0 2 22 * * *", zone = "Asia/Seoul")
    public void generateRefundDetailFile() {
        if (!properties.isBatchEnabled()) {
            log.debug("ZeroPay batch disabled — skipping ZP0066");
            return;
        }
        LocalDate businessDate = LocalDate.now(KST);
        log.info("[Scheduler] ZP0066 start for {}", businessDate);
        try {
            BatchFile file = adapter.generateRefundResultFile(BatchType.ZP0066, businessDate);
            registerTransferAndMark(file, null);
            log.info("[Scheduler] ZP0066 complete: {} records", file.recordCount());
        } catch (Exception e) {
            log.error("[Scheduler] ZP0066 failed for {}: {}", businessDate, e.getMessage(), e);
        }
    }
}
