package com.gme.pay.scheme.zeropay.batch;

import com.gme.pay.scheme.zeropay.adapter.ZeroPayAdapterProperties;
import com.gme.pay.scheme.zeropay.adapter.ZeroPaySchemeAdapter;
import com.gme.pay.scheme.zeropay.adapter.model.BatchFile;
import com.gme.pay.scheme.zeropay.adapter.model.BatchType;
import com.gme.pay.scheme.zeropay.adapter.model.TransferResult;
import com.gme.pay.scheme.zeropay.ops.ZpBatchRunExecutor;
import com.gme.pay.scheme.zeropay.ops.ZpBatchRunTrigger;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;
import org.springframework.boot.autoconfigure.condition.ConditionalOnBean;
import org.springframework.scheduling.annotation.EnableScheduling;
import org.springframework.scheduling.annotation.Scheduled;
import org.springframework.stereotype.Component;

import java.time.Instant;
import java.time.LocalDate;
import java.time.ZoneId;
import java.util.List;
import java.util.Set;

/**
 * KST batch-window scheduler for ZeroPay ZP00xx files.
 *
 * <p>Windows (all times Asia/Seoul, KST = UTC+9):
 * <pre>
 *  ~02:00  ZP0011 payment result   + ZP0021 refund result   → outbound
 *  ~05:00  ZP0061 settlement request (morning)              → outbound
 *  ~14:00  ZP0063 settlement request (afternoon)            → outbound
 *  ~22:00  ZP0065 payment detail   + ZP0066 refund detail   → outbound
 * </pre>
 *
 * <p>Inbound files (ZP0012, ZP0022, ZP0062, ZP0064) are polled by separate fetch jobs
 * or can be triggered manually — they are not generated by the scheduler.</p>
 *
 * <p>The scheduler fires only when
 * {@code gmepay.scheme.zeropay.batch.enabled=true} (default {@code false}).
 * This gate is checked at runtime so no restart is required to re-enable.</p>
 *
 * <p>Requires {@link ZeroPaySchemeAdapter} to be in the Spring context
 * (i.e. {@code adapter.zeropay.enabled=true}).</p>
 *
 * <h2>T3-4: runs are recorded and failures are reported</h2>
 * <p>All six windows now run through {@link ZpBatchRunExecutor}. Previously each ended in its own
 * {@code catch (Exception e) { log.error(...) }} — six copies, no persisted marker, no alert, and no manual
 * trigger to retry with. A failed 02:00 ZP0011 was invisible until KFTC noticed; and because the spec §8.2
 * prerequisite gate blocks ZP0061/ZP0063 until ZP0011 is transmitted and ZP0012 received, that one silent
 * failure also silently stopped the day's settlement requests.
 *
 * <p>Now, per run: a {@code zp_batch_runs} row is committed in its own transaction; a
 * {@code BATCH_RUN_FAILED} CRITICAL alert goes out on the existing {@code gmepay.ops.alert} pipeline (this
 * adapter had no event transport at all before — see {@code ZpOpsAlertConfig}); the configured business-day
 * calendar is consulted; and successful and gate-disabled runs are recorded too, so "did last night's six
 * windows happen?" is answerable. Manual retry is {@code POST /internal/scheme/zeropay/batch/rerun}
 * ({@link com.gme.pay.scheme.zeropay.api.ZeroPayBatchRerunController}).
 */
@Component
@EnableScheduling
@ConditionalOnBean(ZeroPaySchemeAdapter.class)
public class ZeroPayBatchScheduler {

    private static final Logger log = LoggerFactory.getLogger(ZeroPayBatchScheduler.class);
    private static final ZoneId KST = ZoneId.of("Asia/Seoul");

    /** The six OUTBOUND generated windows. Anything else is inbound and not this scheduler's business. */
    public static final Set<BatchType> OUTBOUND_GENERATED = Set.of(
            BatchType.ZP0011, BatchType.ZP0021, BatchType.ZP0061,
            BatchType.ZP0063, BatchType.ZP0065, BatchType.ZP0066);

    private final ZeroPaySchemeAdapter adapter;
    private final ZeroPayAdapterProperties properties;
    /** Persists the batch-file registry around generate/transfer; null in unit slices. */
    private final ZpBatchRegistrar registrar;
    /** Source of the day's records, used to stage ZP0011 detail lines; null in unit slices. */
    private final ZpBatchDataPort batchDataPort;
    /** T3-4 run ledger + calendar + alerting; null in the legacy unit-slice constructor. */
    private final ZpBatchRunExecutor runs;

    /**
     * Transfer outcome of the run on THIS thread. A thread-local rather than a field because the six
     * {@code @Scheduled} methods share Spring's scheduler pool and adjacent windows are only two minutes
     * apart (ZP0065 22:00 / ZP0066 22:02), so a slow run could overlap the next and a shared field would let
     * one window record the other's transfer result.
     */
    private final ThreadLocal<Boolean> lastTransferred = new ThreadLocal<>();

    /** Production constructor (Spring picks this — annotated per the two-ctor convention). */
    @org.springframework.beans.factory.annotation.Autowired
    public ZeroPayBatchScheduler(ZeroPaySchemeAdapter adapter,
                                 ZeroPayAdapterProperties properties,
                                 ZpBatchRegistrar registrar,
                                 ZpBatchDataPort batchDataPort,
                                 ZpBatchRunExecutor runs) {
        this.adapter    = adapter;
        this.properties = properties;
        this.registrar  = registrar;
        this.batchDataPort = batchDataPort;
        this.runs = runs;
    }

    /** Test/legacy constructor without registry or run-ledger wiring. */
    public ZeroPayBatchScheduler(ZeroPaySchemeAdapter adapter,
                                 ZeroPayAdapterProperties properties) {
        this(adapter, properties, null, null, null);
    }

    /**
     * Registers the generated file (GENERATED), transfers it, then marks it TRANSMITTED.
     * Registry writes are best-effort — a registry failure never blocks the transfer.
     *
     * @param file          the generated batch file
     * @param zp0011Records ZP0011 detail records to stage, or null for non-ZP0011 types
     * @return whether the outbound transfer reported success (recorded on the run row)
     */
    private boolean registerTransferAndMark(BatchFile file, List<Zp0011Record> zp0011Records) {
        Long registryId = null;
        if (registrar != null) {
            String fileName = file.fileType().name()
                    + "_" + file.businessDate().toString().replace("-", "")
                    + "_" + String.format("%03d", file.sequenceNo()) + ".dat";
            registryId = registrar.registerGenerated(
                    file, fileName, Instant.now(), Instant.now().plusSeconds(3600), zp0011Records);
        }
        TransferResult result = adapter.transferOutbound(file, null);
        boolean transferred = result != null && result.success();
        if (registrar != null && transferred) {
            registrar.markTransmitted(registryId, Instant.now());
        }
        return transferred;
    }

    // -----------------------------------------------------------------------
    // ~02:00 KST — ZP0011 + ZP0021 (payment/refund result registration)
    // -----------------------------------------------------------------------

    /** Generates and transfers ZP0011 (payment result) at ~02:00 KST. */
    @Scheduled(cron = "0 0 2 * * *", zone = "Asia/Seoul")
    public void generatePaymentResult() {
        runWindow(BatchType.ZP0011, ZpBatchRunTrigger.SCHEDULER, null, null, null);
    }

    /** Generates and transfers ZP0021 (refund result) at ~02:02 KST (2 minutes after ZP0011). */
    @Scheduled(cron = "0 2 2 * * *", zone = "Asia/Seoul")
    public void generateRefundResult() {
        runWindow(BatchType.ZP0021, ZpBatchRunTrigger.SCHEDULER, null, null, null);
    }

    // -----------------------------------------------------------------------
    // ~05:00 / ~14:00 KST — ZP0061 / ZP0063 (settlement requests)
    // -----------------------------------------------------------------------

    /** Generates and transfers ZP0061 (morning settlement request) at ~05:00 KST. */
    @Scheduled(cron = "0 0 5 * * *", zone = "Asia/Seoul")
    public void generateMorningSettlementRequest() {
        runWindow(BatchType.ZP0061, ZpBatchRunTrigger.SCHEDULER, null, null, null);
    }

    /** Generates and transfers ZP0063 (afternoon settlement request) at ~14:00 KST. */
    @Scheduled(cron = "0 0 14 * * *", zone = "Asia/Seoul")
    public void generateAfternoonSettlementRequest() {
        runWindow(BatchType.ZP0063, ZpBatchRunTrigger.SCHEDULER, null, null, null);
    }

    // -----------------------------------------------------------------------
    // ~22:00 KST — ZP0065 + ZP0066 (payment/refund detail)
    // -----------------------------------------------------------------------

    /** Generates and transfers ZP0065 (payment detail) at ~22:00 KST. */
    @Scheduled(cron = "0 0 22 * * *", zone = "Asia/Seoul")
    public void generatePaymentDetailFile() {
        runWindow(BatchType.ZP0065, ZpBatchRunTrigger.SCHEDULER, null, null, null);
    }

    /** Generates and transfers ZP0066 (refund detail) at ~22:02 KST (2 minutes after ZP0065). */
    @Scheduled(cron = "0 2 22 * * *", zone = "Asia/Seoul")
    public void generateRefundDetailFile() {
        runWindow(BatchType.ZP0066, ZpBatchRunTrigger.SCHEDULER, null, null, null);
    }

    /**
     * The one code path all six windows and the manual trigger share.
     *
     * <p>Public so the re-run controller drives a window through exactly the same
     * generate → register → transfer → record → alert sequence a cron does. A separate manual path would be
     * a second implementation that drifts — which is how the original six copies came to differ from each
     * other in the first place.
     *
     * @param type       which ZP00xx window
     * @param trigger    scheduler or operator
     * @param date       business date; null = today (KST)
     * @param operatorId operator attribution, or null
     * @param reason     operator reason, or null
     * @return the run result, or null when the scheduler's feature gate is off (or on a legacy unit slice)
     */
    public ZpBatchRunExecutor.RunResult<BatchFile> runWindow(BatchType type, ZpBatchRunTrigger trigger,
                                                            LocalDate date, String operatorId,
                                                            String reason) {
        LocalDate businessDate = date != null ? date : LocalDate.now(KST);

        // The feature gate applies to the SCHEDULER only. An operator asking explicitly for a re-run has
        // already said what they want; refusing them because a cron is disabled would leave no way to
        // recover a window by hand, which is the hole this gap is about.
        if (trigger == ZpBatchRunTrigger.SCHEDULER && !properties.isBatchEnabled()) {
            log.debug("ZeroPay batch disabled — skipping {}", type);
            if (runs != null) {
                // Recorded, not merely debug-logged: a deployment that never set batch-enabled=true
                // produces NO ZP00xx files at all, and the ledger is the only place that becomes visible.
                runs.recordDisabled(type.name(), businessDate, "adapter.zeropay.batch-enabled=false");
            }
            return null;
        }
        log.info("[Scheduler] {} start for {} (trigger={})", type, businessDate, trigger);

        if (runs == null) {
            // Legacy unit-slice constructor: no ledger, no calendar, no alerting. Preserves the previous
            // log-only behaviour exactly for existing tests rather than NPEing on a half-wired component.
            try {
                BatchFile file = generate(type, businessDate);
                log.info("[Scheduler] {} complete: {} records", type, file.recordCount());
            } catch (Exception e) {
                log.error("[Scheduler] {} failed for {}: {}", type, businessDate, e.getMessage(), e);
            }
            return null;
        }

        return runs.execute(type.name(), businessDate, trigger,
                () -> generate(type, businessDate),
                file -> new ZpBatchRunExecutor.RunSummary(file.recordCount(), takeTransferred()),
                operatorId, reason);
    }

    /** Generate + register + transfer one window. */
    private BatchFile generate(BatchType type, LocalDate businessDate) {
        BatchFile file = switch (type) {
            case ZP0011 -> adapter.generatePaymentResultFile(BatchType.ZP0011, businessDate);
            case ZP0021 -> adapter.generateRefundResultFile(BatchType.ZP0021, businessDate);
            case ZP0061, ZP0063 -> adapter.generateSettlementRequestFile(type, businessDate);
            case ZP0065 -> adapter.generatePaymentResultFile(BatchType.ZP0065, businessDate);
            case ZP0066 -> adapter.generateRefundResultFile(BatchType.ZP0066, businessDate);
            default -> throw new IllegalArgumentException(
                    "not an outbound generated batch type: " + type);
        };
        List<Zp0011Record> staged = (type == BatchType.ZP0011 && batchDataPort != null)
                ? batchDataPort.fetchPaymentRecords(businessDate) : null;
        lastTransferred.set(registerTransferAndMark(file, staged));
        log.info("[Scheduler] {} complete: {} records", type, file.recordCount());
        return file;
    }

    /** Read-and-clear the current thread's transfer outcome (never leaks between runs on a pooled thread). */
    private Boolean takeTransferred() {
        Boolean v = lastTransferred.get();
        lastTransferred.remove();
        return v;
    }
}
