package com.gme.pay.contracts;

import java.util.List;

/**
 * Write shape for one partner webhook subscription — Slice 8 Lane D (wizard
 * step 8, see {@code docs/PARTNER_SETUP_PLAN.md} §"Slice 8"). Carried by
 * {@link PartnerCommand.UpdateStep8WebhookSubscription} onto
 * {@code PATCH /v1/partners/draft/{code}/step-8/webhook-subscription}.
 *
 * <ul>
 *   <li>{@code url} — required; HTTPS URL of the partner's webhook receiver
 *       (&le; 512 chars, must start with {@code https://} — config-registry
 *       validates, the notification-webhook service is the storage-level
 *       backstop).</li>
 *   <li>{@code eventTypes} — event types to subscribe to (e.g.
 *       {@code ["payment.approved", "payment.failed"]}); {@code null} or
 *       empty means "subscribe to all events" (the {@code webhook_endpoint}
 *       NULL-CSV convention).</li>
 *   <li>{@code environment} — which credential environment the subscription
 *       belongs to: {@code SANDBOX} or {@code LIVE}. The draft saved for an
 *       environment is what activation provisions when the partner
 *       transitions into that environment.</li>
 * </ul>
 *
 * <p>The signing secret is intentionally ABSENT here: it is generated by the
 * notification-webhook service at provisioning time (partner activation),
 * stored only as a hash, and surfaced to the operator exactly once via
 * {@link IssuedWebhookSubscription}.
 */
public record WebhookSubscriptionCommand(
        String url,
        List<String> eventTypes,
        String environment) {
}
