-- report_filing: one row per (lane, report_type, report_date) regulatory filing run.
-- Provides an idempotent, auditable record of every report this service generates
-- and (eventually) submits to a government channel — BOK (FX1014/FX1015), KoFIU
-- (CTR/STR daily feed), Hometax (monthly e-tax invoice).
--
-- Idempotency: the natural key (lane, report_type, report_date) is UNIQUE, so a
-- scheduler re-run for the same date is a no-op rather than a duplicate filing.
-- The external submission channels (BOK OI-03, Hometax OI-02 SFTP/mTLS) are
-- externally blocked; submission_status therefore stays GENERATED until a real
-- channel is wired. record_count / file_path / external_receipt_id are populated
-- as the lifecycle advances.

CREATE TABLE report_filing (
    id                   BIGINT       GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    lane                 VARCHAR(16)  NOT NULL,   -- BOK | KOFIU | HOMETAX
    report_type          VARCHAR(16)  NOT NULL,   -- FX1014 | FX1015 | CTR | STR | ETAX
    report_date          DATE         NOT NULL,   -- KST calendar date the filing covers
    record_count         INTEGER      NOT NULL DEFAULT 0,
    submission_status    VARCHAR(16)  NOT NULL DEFAULT 'PENDING',  -- PENDING|GENERATED|SUBMITTED|CONFIRMED|FAILED
    file_path            VARCHAR(512),            -- generated artifact path (NULL until generated)
    external_receipt_id  VARCHAR(128),            -- channel acknowledgement id (NULL until submitted)
    generated_at         TIMESTAMP,
    submitted_at         TIMESTAMP,
    created_at           TIMESTAMP    NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at           TIMESTAMP    NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT ck_report_filing_status
        CHECK (submission_status IN ('PENDING','GENERATED','SUBMITTED','CONFIRMED','FAILED')),
    CONSTRAINT uq_report_filing_natural_key
        UNIQUE (lane, report_type, report_date)
);

CREATE INDEX idx_report_filing_date    ON report_filing (report_date);
CREATE INDEX idx_report_filing_status  ON report_filing (submission_status, report_date);
