-- bok_report_record: one row per cross-border committed transaction requiring
-- BOK FX reporting (DAT-03 §8.1). Domestic (same-currency) transactions are exempt
-- and never produce a row here.
--
-- offer_rate_coll is BOK FX1015 field #14, locked at CommitTransaction:
--   offer_rate_coll = send_amount / (collection_usd - collection_margin_usd)
-- It is carried verbatim from the committed-transaction FX source (never recomputed).
--
-- Idempotency: txn_id is UNIQUE — re-processing the same transaction is a no-op.
-- Each row links back to its report_filing run via filing_id.

CREATE TABLE bok_report_record (
    id                  BIGINT        GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    filing_id           BIGINT        REFERENCES report_filing (id),
    txn_id              BIGINT        NOT NULL,
    txn_ref             VARCHAR(64)   NOT NULL,
    report_type         VARCHAR(10)   NOT NULL,   -- FX1014 | FX1015
    report_date         DATE          NOT NULL,
    partner_id          BIGINT        NOT NULL,
    collection_amount   DECIMAL(20,4),
    collection_ccy      CHAR(3),
    payout_amount       DECIMAL(20,4),
    payout_ccy          CHAR(3),
    offer_rate_coll     DECIMAL(20,8),            -- BOK FX1015 field #14 (locked at commit)
    cross_rate          DECIMAL(20,8),            -- target_payout / send_amount
    usd_amount          DECIMAL(20,4),            -- intermediary USD leg
    submission_status   VARCHAR(20)   NOT NULL DEFAULT 'PENDING',
    submitted_at        TIMESTAMP,
    created_at          TIMESTAMP     NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at          TIMESTAMP     NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT ck_bok_record_type   CHECK (report_type IN ('FX1014','FX1015')),
    CONSTRAINT ck_bok_record_status CHECK (submission_status IN ('PENDING','SUBMITTED','CONFIRMED','FAILED')),
    CONSTRAINT uq_bok_record_txn    UNIQUE (txn_id)
);

COMMENT ON COLUMN bok_report_record.offer_rate_coll IS 'BOK FX1015 field 14 - locked at commit';

CREATE INDEX idx_bok_record_filing ON bok_report_record (filing_id);
CREATE INDEX idx_bok_record_query  ON bok_report_record (report_type, submission_status, report_date);
